/*
Business Question:
How much total revenue is generated by each customer?
*/

SELECT 
	c.Customer_ID,
	SUM(s.Total_Amount) AS Total_Revenue
FROM Sales s
JOIN Customers c
	ON s.Customer_ID = c.Customer_ID
GROUP BY c.Customer_ID
ORDER BY Total_Revenue DESC;



/*
Business Question:
Who are the top 10 highest spending customers?
*/

SELECT TOP 10
	c.Customer_ID,
	SUM(s.Total_Amount) AS Total_Spending
FROM Sales s
JOIN Customers c
	ON s.Customer_ID = c.Customer_ID
GROUP BY c.Customer_ID
ORDER BY Total_Spending DESC;



/*
Business Question:
Do loyalty program members spend more than non-members?
*/

SELECT 
	c.Loyalty_Member,
	SUM(s.Total_Amount) AS Total_Revenue,
	COUNT(s.Sale_ID) AS Total_Transactions
FROM Sales s
JOIN Customers c
	ON s.Customer_ID = c.Customer_ID
GROUP BY c.Loyalty_Member;



/*
Business Question:
What is the average transaction value by customer gender?
*/

SELECT 
	c.Gender,
	AVG(s.Total_Amount) AS Avg_Transaction_Value
FROM Sales s
JOIN Customers c
	ON s.Customer_ID = c.Customer_ID
GROUP BY c.Gender;



/*
Business Question:
Which age group generates the most revenue?
*/

SELECT 
	c.Age_Group,
	SUM(s.Total_Amount) AS Revenue
FROM Sales s
JOIN Customers c
	ON s.Customer_ID = c.Customer_ID
GROUP BY c.Age_Group
ORDER BY Revenue DESC;



/*
Business Question:
How many transactions are made by each customer segment?
*/

SELECT 
	c.Age_Group,
	COUNT(s.Sale_ID) AS Total_Transactions
FROM Sales s
JOIN Customers c
	ON s.Customer_ID = c.Customer_ID
GROUP BY c.Age_Group
ORDER BY Total_Transactions DESC;



/*
Business Question:
Which cities have the highest customer spending?
*/

SELECT 
	c.City,
	SUM(s.Total_Amount) AS Total_Spending
FROM Sales s
JOIN Customers c
	ON s.Customer_ID = c.Customer_ID
GROUP BY c.City
ORDER BY Total_Spending DESC;



/*
Business Question:
Rank customers based on their total spending.
*/

SELECT 
	c.Customer_ID,
	SUM(s.Total_Amount) AS Total_Spending,
	RANK() OVER(
		ORDER BY SUM(s.Total_Amount) DESC
	) AS Customer_Rank
FROM Sales s
JOIN Customers c
	ON s.Customer_ID = c.Customer_ID
GROUP BY c.Customer_ID;



/*
Business Question:
Which customers purchase the highest number of items?
*/

SELECT 
	c.Customer_ID,
	SUM(s.Quantity) AS Total_Items_Purchased
FROM Sales s
JOIN Customers c
	ON s.Customer_ID = c.Customer_ID
GROUP BY c.Customer_ID
ORDER BY Total_Items_Purchased DESC;



/*
Business Question:
What is the average basket size for loyalty vs non-loyalty customers?
*/

SELECT 
	c.Loyalty_Member,
	AVG(s.Quantity) AS Avg_Basket_Size
FROM Sales s
JOIN Customers c
	ON s.Customer_ID = c.Customer_ID
GROUP BY c.Loyalty_Member;
