/*
Business Question:
What is the total revenue generated by the company?
*/

SELECT 
	SUM(Total_Amount) AS Total_Revenue
FROM Sales;



/*
Business Question:
How many total transactions were made across all stores?
*/

SELECT 
	COUNT(Sale_ID) AS Total_Transactions
FROM Sales;



/*
Business Question:
What is the average transaction value (ATV)?
This shows how much customers spend per transaction on average.
*/

SELECT 
	SUM(Total_Amount) / COUNT(Sale_ID) AS Avg_Transaction_Value
FROM Sales;



/*
Business Question:
What is the average number of units purchased per transaction?
This KPI is known as Units Per Transaction (UPT).
*/

SELECT 
	SUM(Quantity) / COUNT(Sale_ID) AS Units_Per_Transaction
FROM Sales;



/*
Business Question:
How much revenue is generated each month?
This helps analyze monthly sales trends.
*/

SELECT 
	FORMAT(Sale_Date,'yyyy-MM') AS Month,
	SUM(Total_Amount) AS Monthly_Revenue
FROM Sales
GROUP BY FORMAT(Sale_Date,'yyyy-MM')
ORDER BY Month;



/*
Business Question:
How much revenue is generated each year?
This helps track long-term business growth.
*/

SELECT 
	YEAR(Sale_Date) AS Year,
	SUM(Total_Amount) AS Yearly_Revenue
FROM Sales
GROUP BY YEAR(Sale_Date)
ORDER BY Year;



/*
Business Question:
What is the average number of items purchased in a transaction?
This is also known as the average basket size.
*/

SELECT 
	AVG(Quantity) AS Avg_Items_Per_Transaction
FROM Sales;



/*
Business Question:
Which payment methods are most commonly used by customers?
*/

SELECT 
	Payment_Method,
	COUNT(*) AS Total_Transactions
FROM Sales
GROUP BY Payment_Method
ORDER BY Total_Transactions DESC;



/*
Business Question:
How do discounts affect revenue?
This analysis shows revenue generated at different discount levels.
*/

SELECT 
	Discount,
	SUM(Total_Amount) AS Revenue
FROM Sales
GROUP BY Discount
ORDER BY Discount;



/*
Business Question:
What are the monthly revenue trends over time?
This helps identify seasonality and peak sales periods.
*/

SELECT 
	YEAR(Sale_Date) AS Year,
	MONTH(Sale_Date) AS Month,
	SUM(Total_Amount) AS Revenue
FROM Sales
GROUP BY 
YEAR(Sale_Date),
MONTH(Sale_Date)
ORDER BY Year, Month;
