/*
Business Question:
Which stores generate the highest total revenue?
*/

SELECT 
	st.Store_Name,
	SUM(s.Total_Amount) AS Total_Revenue
FROM Sales s
JOIN Stores st
	ON s.Store_ID = st.Store_ID
GROUP BY st.Store_Name
ORDER BY Total_Revenue DESC;



/*
Business Question:
What is the total revenue generated by each store?
*/

SELECT 
	st.Store_ID,
	st.Store_Name,
SUM(s.Total_Amount) AS Store_Revenue
FROM Sales s
JOIN Stores st
	ON s.Store_ID = st.Store_ID
GROUP BY st.Store_ID, st.Store_Name
ORDER BY Store_Revenue DESC;



/*
Business Question:
How many transactions does each store handle?
*/

SELECT 
	st.Store_Name,
	COUNT(s.Sale_ID) AS Total_Transactions
FROM Sales s
JOIN Stores st
	ON s.Store_ID = st.Store_ID
GROUP BY st.Store_Name
ORDER BY Total_Transactions DESC;



/*
Business Question:
What is the average transaction value for each store?
*/

SELECT 
	st.Store_Name,
	AVG(s.Total_Amount) AS Avg_Transaction_Value
FROM Sales s
JOIN Stores st
	ON s.Store_ID = st.Store_ID
GROUP BY st.Store_Name
ORDER BY Avg_Transaction_Value DESC;



/*
Business Question:
How much revenue does each region generate?
*/

SELECT 
	st.Region,
SUM(s.Total_Amount) AS Regional_Revenue
FROM Sales s
JOIN Stores st
	ON s.Store_ID = st.Store_ID
GROUP BY st.Region
ORDER BY Regional_Revenue DESC;



/*
Business Question:
Which cities generate the highest retail revenue?
*/

SELECT 
	st.City,
SUM(s.Total_Amount) AS City_Revenue
FROM Sales s
	JOIN Stores st
ON s.Store_ID = st.Store_ID
GROUP BY st.City
ORDER BY City_Revenue DESC;



/*
Business Question:
Which store types generate the most revenue?
Example store types: Mall, Street, Hypermarket.
*/

SELECT 
	st.Store_Type,
SUM(s.Total_Amount) AS Revenue
FROM Sales s
JOIN Stores st
	ON s.Store_ID = st.Store_ID
GROUP BY st.Store_Type
ORDER BY Revenue DESC;



/*
Business Question:
Which stores sell the most units?
*/

SELECT 
	st.Store_Name,
SUM(s.Quantity) AS Total_Units_Sold
FROM Sales s
JOIN Stores st
	ON s.Store_ID = st.Store_ID
GROUP BY st.Store_Name
ORDER BY Total_Units_Sold DESC;



/*
Business Question:
Rank stores based on total revenue.
*/

SELECT 
	st.Store_Name,
	SUM(s.Total_Amount) AS Revenue,
	RANK() OVER (ORDER BY SUM(s.Total_Amount) DESC) AS Store_Rank
FROM Sales s
JOIN Stores st
	ON s.Store_ID = st.Store_ID
GROUP BY st.Store_Name;



/*
Business Question:
Which stores perform best within each region?
*/

SELECT 
	st.Region,
	st.Store_Name,
	SUM(s.Total_Amount) AS Revenue,
	RANK() OVER(
		PARTITION BY st.Region
		ORDER BY SUM(s.Total_Amount) DESC
	) AS Regional_Rank
FROM Sales s
JOIN Stores st
	ON s.Store_ID = st.Store_ID
GROUP BY st.Region, st.Store_Name;
